/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p2_piedrapapeltijera;

import javax.swing.SwingUtilities;

/**
 *
 * @author Alejandro Campos Maestre
 */
public class ventana extends javax.swing.JFrame
{

    logicaPrincipal logica = new logicaPrincipal();

    /**
     * Creates new form logica
     */
    public ventana()
    {
        super("Juego de Piedra, papel, tijera, lagarto, Spok");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        piedra = new javax.swing.JButton();
        papel = new javax.swing.JButton();
        tijera = new javax.swing.JButton();
        lagarto = new javax.swing.JButton();
        Spok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        piedra.setText("Piedra");
        piedra.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                piedraActionPerformed(evt);
            }
        });

        papel.setText("Papel");
        papel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                papelActionPerformed(evt);
            }
        });

        tijera.setText("Tijera");
        tijera.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tijeraActionPerformed(evt);
            }
        });

        lagarto.setText("Lagarto");
        lagarto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                lagartoActionPerformed(evt);
            }
        });

        Spok.setText("Spock");
        Spok.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SpokActionPerformed(evt);
            }
        });

        jLabel1.setText("Elija una de las 5 opciones:");

        jLabel2.setText("Victorias: Jugador "+logica.getvJugador()+" vs maquina "+logica.getvMaquina());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(piedra)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(papel)
                        .addGap(18, 18, 18)
                        .addComponent(tijera)
                        .addGap(18, 18, 18)
                        .addComponent(lagarto)
                        .addGap(18, 18, 18)
                        .addComponent(Spok)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(piedra)
                    .addComponent(papel)
                    .addComponent(tijera)
                    .addComponent(lagarto)
                    .addComponent(Spok))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void piedraActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_piedraActionPerformed
    {//GEN-HEADEREND:event_piedraActionPerformed
        logica.jugada(0);
        actualizarPantalla();
    }//GEN-LAST:event_piedraActionPerformed

    private void papelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_papelActionPerformed
    {//GEN-HEADEREND:event_papelActionPerformed
        logica.jugada(1);
        actualizarPantalla();
    }//GEN-LAST:event_papelActionPerformed

    private void tijeraActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tijeraActionPerformed
    {//GEN-HEADEREND:event_tijeraActionPerformed
        logica.jugada(2);
        actualizarPantalla();
    }//GEN-LAST:event_tijeraActionPerformed

    private void lagartoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lagartoActionPerformed
    {//GEN-HEADEREND:event_lagartoActionPerformed
        logica.jugada(3);
        actualizarPantalla();
    }//GEN-LAST:event_lagartoActionPerformed

    private void SpokActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SpokActionPerformed
    {//GEN-HEADEREND:event_SpokActionPerformed
        logica.jugada(4);
        actualizarPantalla();
    }//GEN-LAST:event_SpokActionPerformed

    public void actualizarPantalla()
    {
        this.remove(jLabel2);
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Spok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton lagarto;
    private javax.swing.JButton papel;
    private javax.swing.JButton piedra;
    private javax.swing.JButton tijera;
    // End of variables declaration//GEN-END:variables
}
